name: Weekly Release

on:
  schedule:
    # Каждое воскресенье в 21:00 по МСК
    - cron: '0 18 * * 0'
  workflow_dispatch:

jobs:
  merge-dev-to-master:
    name: Merge dev to master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout master branch
        run: git checkout master

      - name: Merge dev into master
        run: |
          git merge origin/dev --no-edit

      - name: Push changes to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin master
