name: Auto Merge Dev to Master

on:
  workflow_dispatch:
  schedule:
    - cron: '45 22 * * 3'

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Backup master branch
        run: |
          current_date=$(date +%Y-%m-%d)
          git checkout master
          git branch master-backup-$current_date
          git push origin master-backup-$current_date

      - name: Switch to master branch
        run: git checkout master

      - name: Merge dev into master
        run: |
          git merge origin/dev --no-edit || exit 0

      - name: Push changes (if no conflicts)
        if: ${{ success() }}
        run: git push origin master

      - name: Create a Pull Request if merge fails
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge dev into master (conflict PR)'
          branch: auto/merge-dev-to-master
          base: master
          title: 'Auto PR: Merge dev into master'
          body: |
            This pull request was created automatically because the direct merge of `dev` into `master` resulted in conflicts.
            Please resolve the conflicts and merge manually.
